In [78]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df=pd.read_csv(r'C:\Users\YN Computer\Desktop\My Projects\Agricultural\Data\Crop Wise Area Production Yield_Sample_Data.csv')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Year (year)                        500 non-null    str
 1   State Name (state_name)            500 non-null    str
 2   State Code (state_code)            500 non-null    int64
 3   District Name (district_name)      500 non-null    str
 4   District Code (district_code)      500 non-null    int64
 5   Crop Name (crop_name)              500 non-null    str
 6   Crop Code (crop_code)              500 non-null    float64
 7   Crop Type (crop_type)              500 non-null    str
 8   Season (season)                    500 non-null    str
 9   Area (area)                        500 non-null    float64
 10  Area Unit (area_unit)              500 non-null    str
 11  Production (production)            491 non-null    float64
 12  Production Unit (production_unit)  500 non-null    str
 13  Yield (yield)                      500 non-null    float64
 14  Yield Unit (yield_unit)            500 non-null    str
dtypes: float64(4), int64(2), str(9)
memory usage: 58.7 KB

In [10]:
df.head()

,Year (year),State Name (state_name),State Code (state_code),District Name (district_name),District Code (district_code),Crop Name (crop_name),Crop Code (crop_code),Crop Type (crop_type),Season (season),Area (area),Area Unit (area_unit),Production (production),Production Unit (production_unit),Yield (yield),Yield Unit (yield_unit)
0,2002-2003,Telangana,36,Nalgonda,514,Groundnut,1001.0,Oilseeds,Rabi,9510.0,Hectare,7361.0,Tonnes,0.774,Tonnes/Hectare
1,2013-2014,Tamil Nadu,33,Namakkal,580,Rapeseed &Mustard,1004.0,Oilseeds,Rabi,5.0,Hectare,1.0,Tonnes,0.200,Tonnes/Hectare
2,2002-2003,Rajasthan,8,Jhalawar,105,Other Kharif Pulses,288.0,Pulses,Kharif,114.0,Hectare,11.0,Tonnes,0.096,Tonnes/Hectare
3,2009-2010,Uttar Pradesh,9,Ghaziabad,145,Urad,203.0,Pulses,Summer,124.0,Hectare,77.0,Tonnes,0.621,Tonnes/Hectare
4,2019-2020,Nagaland,13,Tuensang,249,Sugarcane,401.0,Sugar,Kharif,370.0,Hectare,16135.0,Tonnes,43.608,Tonnes/Hectare

In [26]:
df=df.rename(columns={
    "Year (year)":"Year","State Name (state_name)":"State Name","State Code (state_code)":"State Code","District Name (district_name)":"District Name","District Code (district_code)":"District Code","Crop Name (crop_name)":"Crop Name","Crop Code (crop_code)":"Crop Code","Crop Type (crop_type)":"Crop Type","Season (season)":"Season","Area (area)":"Area","Area Unit (area_unit)":"Area Unit","Production (production)":"Production","Production Unit (production_unit)":"Production Unit","Yield (yield)":"Yield","Yield Unit (yield_unit)":"Yield Unit"
})

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             500 non-null    str
 1   State Name       500 non-null    str
 2   State Code       500 non-null    int64
 3   District Name    500 non-null    str
 4   District Code    500 non-null    int64
 5   Crop Name        500 non-null    str
 6   Crop Code        500 non-null    float64
 7   Crop Type        500 non-null    str
 8   Season           500 non-null    str
 9   Area             500 non-null    float64
 10  Area Unit        500 non-null    str
 11  Production       491 non-null    float64
 12  Production Unit  500 non-null    str
 13  Yield            500 non-null    float64
 14  Yield Unit       500 non-null    str
dtypes: float64(4), int64(2), str(9)
memory usage: 58.7 KB

In [45]:
df[df['Production'].isnull()==True]

,Year,State Name,State Code,District Name,District Code,Crop Name,Crop Code,Crop Type,Season,Area,Area Unit,Production,Production Unit,Yield,Yield Unit
39,2018-2019,Tamil Nadu,33,Chennai,568,Sesamum,1003.0,Oilseeds,Kharif,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
44,2002-2003,Kerala,32,Kannur,557,Sesamum,1003.0,Oilseeds,Kharif,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
63,2002-2003,Uttarakhand,5,Tehri Garhwal,55,Other Oilseeds,1088.0,Oilseeds,Rabi,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
101,2018-2019,Chhattisgarh,22,Mungeli,647,Ginger,503.0,Spices,Whole Year,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
119,2005-2006,Rajasthan,8,Ganganagar,100,Other Kharif Pulses,288.0,Pulses,Kharif,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
198,2009-2010,Haryana,6,Sonipat,75,Sweet Potato,703.0,Vegetable,Whole Year,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
220,2014-2015,Tamil Nadu,33,Dindigul,572,Rapeseed &Mustard,1004.0,Oilseeds,Rabi,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
237,2019-2020,Punjab,3,Ludhiana,36,Moong(Green Gram),204.0,Pulses,Kharif,100.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare
241,2015-2016,Chhattisgarh,22,Bijapur,636,Coriander,509.0,Spices,Whole Year,1.0,Hectare,NaN,Tonnes,0.0,Tonnes/Hectare

In [47]:
df["Production"] = df["Production"].fillna(0)

In [52]:
df["Yield Unit"].isnull().sum()

np.int64(0)

In [53]:
print(df.isna().mean() * 100)

Year               0.0
State Name         0.0
State Code         0.0
District Name      0.0
District Code      0.0
Crop Name          0.0
Crop Code          0.0
Crop Type          0.0
Season             0.0
Area               0.0
Area Unit          0.0
Production         0.0
Production Unit    0.0
Yield              0.0
Yield Unit         0.0
dtype: float64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             500 non-null    str
 1   State Name       500 non-null    str
 2   State Code       500 non-null    int64
 3   District Name    500 non-null    str
 4   District Code    500 non-null    int64
 5   Crop Name        500 non-null    str
 6   Crop Code        500 non-null    float64
 7   Crop Type        500 non-null    str
 8   Season           500 non-null    str
 9   Area             500 non-null    float64
 10  Area Unit        500 non-null    str
 11  Production       500 non-null    float64
 12  Production Unit  500 non-null    str
 13  Yield            500 non-null    float64
 14  Yield Unit       500 non-null    str
dtypes: float64(4), int64(2), str(9)
memory usage: 58.7 KB

In [106]:
import numpy as np

# Ensure numeric fields are numeric
df["Area"] = pd.to_numeric(df["Area"], errors="coerce")
df["Production"] = pd.to_numeric(df["Production"], errors="coerce")
df["Yield"] = pd.to_numeric(df["Yield"], errors="coerce")

# Clean Year and create start_year
df["Year"] = df["Year"].astype("string").str.strip()

df["start_year"] = (
    df["Year"]
    .str.split("-")
    .str[0]
    .astype("Int64")
)

# Create a clean analysis dataset:
# keep records with area and production available and valid
analysis_df = df[
    (df["Area"].notna()) &
    (df["Production"].notna()) &
    (df["Area"] > 0) &
    (df["Production"] >= 0)
].copy()

# Recalculate yield from Area and Production
analysis_df["calculated_yield"] = (
    analysis_df["Production"] / analysis_df["Area"]
)

In [107]:
total_production = analysis_df["Production"].sum()
total_area = analysis_df["Area"].sum()
overall_yield = total_production / total_area

number_of_states = analysis_df["State Name"].nunique()
number_of_districts = analysis_df["District Name"].nunique()
number_of_crops = analysis_df["Crop Name"].nunique()

latest_crop_year = (
    analysis_df.loc[
        analysis_df["start_year"].idxmax(),
        "Year"
    ]
)

print("Total Production:", total_production)
print("Total Area:", total_area)
print("Overall Yield:", overall_yield)
print("States:", number_of_states)
print("Districts:", number_of_districts)
print("Crops:", number_of_crops)
print("Latest Crop Year:", latest_crop_year)

Total Production: 119130902.614
Total Area: 5299723.04
Overall Yield: 22.47870345579417
States: 29
Districts: 342
Crops: 61
Latest Crop Year: 2022-2023

In [108]:
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Production (Tonnes)",
        "Total Cultivated Area (Hectares)",
        "Overall Yield (Tonnes/Hectare)",
        "Number of States",
        "Number of Districts",
        "Number of Crops",
        "Latest Crop Year"
    ],
    "Value": [
        round(total_production, 2),
        round(total_area, 2),
        round(overall_yield, 3),
        number_of_states,
        number_of_districts,
        number_of_crops,
        latest_crop_year
    ]
})

kpi_summary

                                KPI         Value
0         Total Production (Tonnes)  119130902.61
1  Total Cultivated Area (Hectares)    5299723.04
2    Overall Yield (Tonnes/Hectare)        22.479
3                  Number of States            29
4               Number of Districts           342
5                   Number of Crops            61
6                  Latest Crop Year     2022-2023

In [109]:
# Production trend by crop year
year_summary = (
    analysis_df.groupby(["start_year", "Year"], as_index=False)
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum")
    )
    .sort_values("start_year")
)

year_summary["weighted_yield"] = (
    year_summary["total_production"] /
    year_summary["total_area"]
)

# Production by crop type
crop_type_summary = (
    analysis_df.groupby("Crop Type", as_index=False)
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum")
    )
)

crop_type_summary["weighted_yield"] = (
    crop_type_summary["total_production"] /
    crop_type_summary["total_area"]
)

crop_type_summary = crop_type_summary.sort_values(
    "total_production",
    ascending=False
)

# Top 10 states by production
state_summary = (
    analysis_df.groupby("State Name", as_index=False)
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum"),
        district_count=("District Name", "nunique")
    )
)

state_summary["weighted_yield"] = (
    state_summary["total_production"] /
    state_summary["total_area"]
)

state_summary = state_summary.sort_values(
    "total_production",
    ascending=False
)

top_10_states = state_summary.head(10)

# Top 10 crops by production
crop_summary = (
    analysis_df.groupby(["Crop Name", "Crop Type"], as_index=False)
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum")
    )
)

crop_summary["weighted_yield"] = (
    crop_summary["total_production"] /
    crop_summary["total_area"]
)

crop_summary = crop_summary.sort_values(
    "total_production",
    ascending=False
)

top_10_crops = crop_summary.head(10)

In [110]:
# Top 10 crops by yield
top_10_yield_crops = (
    crop_summary[
        crop_summary["total_area"] >= 100
    ]
    .sort_values("weighted_yield", ascending=False)
    .head(10)
)

# Top 10 crops by cultivated area
top_10_area_crops = (
    crop_summary
    .sort_values("total_area", ascending=False)
    .head(10)
)

# Add production rank for a detailed crop table
crop_performance_table = crop_summary.copy()

crop_performance_table["production_rank"] = (
    crop_performance_table["total_production"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

crop_performance_table = crop_performance_table.sort_values(
    "production_rank"
)

In [111]:
# State ranking by yield
state_yield_ranking = (
    state_summary[
        state_summary["total_area"] >= 1000
    ]
    .sort_values("weighted_yield", ascending=False)
)

# District-level performance
district_summary = (
    analysis_df.groupby(
        ["State Name", "District Name"],
        as_index=False
    )
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum"),
        crops_count=("Crop Name", "nunique")
    )
)

district_summary["weighted_yield"] = (
    district_summary["total_production"] /
    district_summary["total_area"]
)

district_summary["production_rank_in_state"] = (
    district_summary.groupby("State Name")["total_production"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

district_summary = district_summary.sort_values(
    ["State Name", "production_rank_in_state"]
)

In [112]:
season_summary = (
    analysis_df.groupby("Season", as_index=False)
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum")
    )
)

season_summary["weighted_yield"] = (
    season_summary["total_production"] /
    season_summary["total_area"]
)

season_summary = season_summary.sort_values(
    "total_production",
    ascending=False
)

season_crop_type_matrix = (
    analysis_df.groupby(
        ["Season", "Crop Type"],
        as_index=False
    )
    .agg(
        total_production=("Production", "sum"),
        total_area=("Area", "sum")
    )
)

season_crop_type_matrix["weighted_yield"] = (
    season_crop_type_matrix["total_production"] /
    season_crop_type_matrix["total_area"]
)

In [113]:
data_quality_summary = pd.DataFrame({
    "Data Quality Check": [
        "Total Records",
        "Missing Area",
        "Missing Production",
        "Missing Yield",
        "Zero Production",
        "Zero Yield",
        "Duplicate Rows",
        "Invalid Crop Year",
        "Non-Tonnes Production Units",
        "Non-Hectare Area Units"
    ],
    "Count": [
        len(df),
        df["Area"].isna().sum(),
        df["Production"].isna().sum(),
        df["Yield"].isna().sum(),
        (df["Production"] == 0).sum(),
        (df["Yield"] == 0).sum(),
        df.duplicated().sum(),
        (~df["Year"].str.match(r"^\d{4}-\d{4}$", na=False)).sum(),
        (df["Production Unit"] != "Tonnes").sum(),
        (df["Area Unit"] != "Hectare").sum()
    ]
})

data_quality_summary

            Data Quality Check  Count
0                Total Records    500
1                 Missing Area      0
2           Missing Production      0
3                Missing Yield      0
4              Zero Production     11
5                   Zero Yield     11
6               Duplicate Rows      0
7            Invalid Crop Year      0
8  Non-Tonnes Production Units      0
9       Non-Hectare Area Units      0

In [114]:
analysis_df.to_csv("agriculture_cleaned_data.csv", index=False)

kpi_summary.to_csv("kpi_summary.csv", index=False)
year_summary.to_csv("year_summary.csv", index=False)
crop_type_summary.to_csv("crop_type_summary.csv", index=False)

state_summary.to_csv("state_summary.csv", index=False)
top_10_states.to_csv("top_10_states.csv", index=False)

crop_performance_table.to_csv("crop_performance_table.csv", index=False)
top_10_crops.to_csv("top_10_crops.csv", index=False)
top_10_yield_crops.to_csv("top_10_yield_crops.csv", index=False)
top_10_area_crops.to_csv("top_10_area_crops.csv", index=False)

district_summary.to_csv("district_summary.csv", index=False)
season_summary.to_csv("season_summary.csv", index=False)
season_crop_type_matrix.to_csv("season_crop_type_matrix.csv", index=False)

data_quality_summary.to_csv("data_quality_summary.csv", index=False)